{
 "title": "crypto-sync debug",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "hist_positions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "select * from hist_positions WHERE size != 0"
    }
   ]
  },
  {
   "title": "orders",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "rawSql": "select * from orders" }
   ]
  },
  {
   "title": "hist_collaterals",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "rawSql": "select * from hist_collaterals" }
   ]
  }
 ]
}