{
 "title": "crypto-sync",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account",
    "query": "SELECT DISTINCT account FROM hist_collaterals"
   }
  ]
 },
 "panels": [
  {
   "title": "return %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nfetched_at as time,\n((1e-37 + collateral) / (1e-37 + FIRST_VALUE(collateral) OVER (PARTITION BY account ORDER BY fetched_at)) - 1) * 100 as \" \",\naccount\nFROM hist_collaterals AS t1\nWHERE $__unixEpochFilter(fetched_at / 1000)\nORDER by fetched_at, account"
    }
   ]
  },
  {
   "title": "collaterals usd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nfetched_at as time,\ncollateral as \" \",\naccount\nFROM hist_collaterals AS t1\nWHERE currency = 'USD' AND $__unixEpochFilter(fetched_at / 1000)\nORDER by fetched_at, account"
    }
   ]
  },
  {
   "title": "collaterals jpy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\nfetched_at as time,\ncollateral as \" \",\naccount\nFROM hist_collaterals AS t1\nWHERE currency = 'JPY' AND $__unixEpochFilter(fetched_at / 1000)\nORDER by fetched_at, account"
    }
   ]
  },
  { "title": "account $account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "account" },
  {
   "title": "positions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\nfetched_at as time,\n(CASE WHEN symbol LIKE '%:%' AND symbol NOT LIKE '%:USD%' AND symbol NOT LIKE '%:JPY%' THEN size / mark_price ELSE size * mark_price END) as \" \",\nsymbol \nfrom hist_positions \nwhere account = $account AND $__unixEpochFilter(fetched_at / 1000)\norder by fetched_at, symbol"
    }
   ]
  },
  {
   "title": "leverage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\nt1.fetched_at as time,\n(CASE WHEN symbol LIKE '%:%' AND symbol NOT LIKE '%:USD%' AND symbol NOT LIKE '%:JPY%' THEN size / mark_price ELSE size * mark_price END) / t2.collateral as \" \", \nsymbol\nFROM hist_positions AS t1\nINNER JOIN hist_collaterals AS t2 ON t1.fetched_at = t2.fetched_at AND t1.account = t2.account\nWHERE t1.account = $account AND $__unixEpochFilter(t1.fetched_at / 1000)\nORDER by t1.fetched_at, symbol"
    }
   ]
  },
  {
   "title": "orders",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n*\nFROM orders AS t1\nWHERE t1.account = $account AND $__unixEpochFilter(fetched_at / 1000)\nORDER BY t1.fetched_at, symbol"
    }
   ]
  },
  {
   "title": "total leverage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\nt1.fetched_at as time,\nsum(abs(CASE WHEN symbol LIKE '%:%' AND symbol NOT LIKE '%:USD%' AND symbol NOT LIKE '%:JPY%' THEN size / mark_price ELSE size * mark_price END) / t2.collateral) as \" \"\nFROM hist_positions AS t1\nINNER JOIN hist_collaterals AS t2 ON t1.fetched_at = t2.fetched_at AND t1.account = t2.account\nWHERE t1.account = $account AND $__unixEpochFilter(t1.fetched_at / 1000)\nGROUP BY t1.fetched_at\nORDER by t1.fetched_at"
    }
   ]
  }
 ]
}